---
title: Composers
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    year: YEAR
markdown: kramdown
highlighter: rouge
lsi: false
description: your resume
baseurl: "/jekyll-timeline"
url: http://himsel.me
color: "#f2f2f2"
